In [1]:
import json
import os
import time
from pathlib import Path

import numpy as np
import pandas as pd
import requests
import yaml
from box import ConfigBox
from sklearn.metrics import f1_score
from tqdm import tqdm

### Set web serice URL

In [2]:
# local testing
API_URL = "http://0.0.0.0:8080" 
# testing deployed service
# API_URL = "https://<YOUR_APP_NAME>.fly.dev" 

API_URL

'http://0.0.0.0:8080'

### Load feature columns and data

In [3]:
def load_params(params_path):
    with open(params_path, "r") as f:
        params = yaml.safe_load(f)
        params = ConfigBox(params)
    return params


proj_path = Path(os.getcwd()).parent.absolute()
params = load_params(proj_path/'params.yaml')
feat_cols = params.base.feat_cols
targ_col = params.base.targ_col
feat_cols, targ_col

(BoxList(['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary']),
 'Exited')

In [4]:
df = pd.concat([pd.read_csv(proj_path/'data'/'raw'/f'Churn_Modelling_{country}.csv') for country in ['France', 'Spain']])
df.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
2,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
3,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
4,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0

### Test `/predict` endpoint by sending one sample request

In [5]:
my_obj = {
    "data": [
            {
      "CreditScore": 619,
      "Age": 42,
      "Tenure": 2,
      "Balance": 0,
      "NumOfProducts": 1,
      "HasCrCard": 1,
      "IsActiveMember": 1,
      "EstimatedSalary": 101348.88
            }
        ]
    }
x = requests.post(API_URL + '/predict', json = my_obj)
if x.ok:
    probs = x.json()
else:
    x.raise_for_status()

probs

[0.7238478660583496]

### Create a functions for calling `/predict` endpoint

In [6]:
def get_prob(obj):
    x = requests.post(API_URL + '/predict', json = obj)
    if x.ok:
        probs = x.json()
    else:
        x.raise_for_status()
    return probs

get_prob(my_obj)

[0.7238478660583496]

### Check what would f1-scores look like if we send the data from the same geographies that the model was trained on

In [7]:
import time


def send_sample_requests(df):
    f1_score_list = []
    for _ in tqdm(range(50)):
        df_sample = df.sample(n=60)
        y_true = df_sample[targ_col].values
        obj = {"data": df_sample[feat_cols].to_dict('records')}
        probs = get_prob(obj)
        y_pred = np.array([prob < 0.5 for prob in probs]).astype(int)
        f1 = f1_score(y_true, y_pred)
        f1_score_list.append(f1)
        time.sleep(1)
    return f1_score_list
        
f1_score_list = send_sample_requests(df)
f1_score_list

100%|██████████| 50/50 [00:51<00:00,  1.03s/it]

[1.0,
 1.0,
 0.9,
 0.8888888888888888,
 0.8571428571428572,
 0.8,
 0.8235294117647058,
 1.0,
 0.9,
 0.9600000000000001,
 0.7272727272727272,
 0.9411764705882353,
 1.0,
 0.888888888888889,
 0.8666666666666666,
 1.0,
 0.9,
 0.9411764705882353,
 0.8,
 0.8571428571428572,
 0.9411764705882353,
 0.7200000000000001,
 1.0,
 0.8181818181818182,
 0.9090909090909091,
 0.8799999999999999,
 1.0,
 1.0,
 1.0,
 0.9090909090909091,
 0.923076923076923,
 0.8421052631578948,
 0.8571428571428571,
 0.9090909090909091,
 0.8750000000000001,
 0.9473684210526316,
 0.923076923076923,
 0.9565217391304348,
 0.8,
 0.8181818181818182,
 1.0,
 0.8695652173913043,
 0.9473684210526316,
 0.9473684210526316,
 0.782608695652174,
 0.7499999999999999,
 0.9600000000000001,
 1.0,
 0.9411764705882353,
 0.9473684210526316]

### What would f1-scores look like for input data from new geography?

In [8]:
df_germany =  pd.read_csv(proj_path/'data'/'more_data'/'Churn_Modelling_Germany.csv')
time.sleep(20) # this is to create a pause between requests. Later it'll be easier to distinguish the two types if requests
f1_score_list = send_sample_requests(df_germany)
f1_score_list

100%|██████████| 50/50 [00:51<00:00,  1.03s/it]

[0.6399999999999999,
 0.45161290322580644,
 0.5000000000000001,
 0.42424242424242425,
 0.56,
 0.5714285714285714,
 0.45161290322580644,
 0.5333333333333333,
 0.5925925925925926,
 0.43750000000000006,
 0.3888888888888889,
 0.35714285714285715,
 0.3870967741935484,
 0.4166666666666667,
 0.625,
 0.56,
 0.5185185185185185,
 0.5161290322580644,
 0.3448275862068965,
 0.4347826086956522,
 0.4,
 0.45714285714285713,
 0.38095238095238093,
 0.4444444444444445,
 0.5714285714285714,
 0.24,
 0.6341463414634146,
 0.32,
 0.47058823529411764,
 0.36363636363636365,
 0.48,
 0.3225806451612903,
 0.48,
 0.6666666666666666,
 0.33333333333333326,
 0.4444444444444444,
 0.5,
 0.37037037037037035,
 0.4666666666666667,
 0.6470588235294118,
 0.4848484848484849,
 0.4166666666666667,
 0.3333333333333333,
 0.5,
 0.5714285714285714,
 0.6153846153846153,
 0.5,
 0.6451612903225806,
 0.46153846153846156,
 0.6285714285714286]

### ... as expected, the values are much lower.
### But, typically, we can't compute model metrics on production data right away 
### because ground truth labels might not be available until much-much later

### All we can do is try and look at "proxy" metrics that measure statistical differences (distances) between train data and production data

In [9]:
x = requests.get(API_URL + '/drift_data')
if x.ok:
    data = x.json()
else:
    x.raise_for_status()

df_p_vals = pd.DataFrame(json.loads(data))
df_p_vals

,time,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,2023-11-26 18:22:40.353619,0.056052,0.686653,0.939705,5.695101e-01,0.809287,0.980594,0.910661,0.048197
1,2023-11-26 18:22:41.376518,0.418407,0.999710,0.993417,9.566445e-01,1.000000,1.000000,1.000000,0.690635
2,2023-11-26 18:22:42.399682,0.184935,0.424908,0.977552,1.261692e-01,1.000000,1.000000,1.000000,0.588342
3,2023-11-26 18:22:43.414669,0.846728,0.507833,0.916845,1.219726e-01,0.750037,1.000000,0.497856,0.712396
4,2023-11-26 18:22:44.434564,0.694810,0.831117,0.632786,7.431123e-01,0.995000,0.993182,0.962630,0.225462
...,...,...,...,...,...,...,...,...,...
95,2023-11-26 18:24:38.080706,0.582044,0.176634,0.953986,3.006232e-16,0.534482,0.953637,0.999978,0.223568
96,2023-11-26 18:24:39.108848,0.257154,0.431466,0.999945,6.152511e-16,0.345591,0.953637,0.102876,0.516075
97,2023-11-26 18:24:40.142169,0.818738,0.096427,0.999936,0.000000e+00,0.986895,0.915592,0.712223,0.329081
98,2023-11-26 18:24:41.173252,0.176795,0.272687,0.535237,0.000000e+00,0.345591,0.915592,0.712223,0.753401
99,2023-11-26 18:24:42.202681,0.676599,0.073998,0.952738,0.000000e+00,0.206561,0.993182,0.901523,0.635583

### Values below the threshold (e.g. 0.05) indicate data drift

In [10]:
import plotly_express as px

fig = px.line(df_p_vals, x='time', y=feat_cols)
fig.add_hline(y=0.05, line_color='red')